{
  "props": [],
  "components": {
    "ini": {
      "type": "script\\storage\\IniStorage",
      "x": 48,
      "y": 48,
      "props": {
        "path": "settings.cfg",
        "autoSave": "1",
        "multiLineValues": "1"
      }
    },
    "fileChooser": {
      "type": "script\\FileChooserScript",
      "x": 288.0,
      "y": 16.0,
      "props": {
        "initialFileName": "Выбор фона",
        "filterName": "PNG",
        "filterExtensions": "*.png",
        "filterAny": "0",
        "inputNode": "edit",
        "actionNode": "button4"
      }
    }
  }
}